version: '2'
services:
  server:
    build: ./src/server
    image: flask:latest
    ports:
      - "8081:8081"
    volumes:
      - ./src/server/flask_app:/server/flask_app/
    environment:
      - FLASK_CONFIGURATION
    container_name: flask-backend
  client:
    build: ./src/client
    image: angular2:latest
    container_name: angular2-frontend
    ports:
      - "3000:8080"
    links:
      - server
    depends_on:
      - server
