version: '2'
services:
  server:
    build: ./src/server
    image: ADS-Flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./src/server/flask_app:/server/flask_app/
    environment:
      - FLASK_CONFIGURATION
    container_name: Flask-backend
  client:
    build: ./src/client
    image: ADS-Frontend
    container_name: Web-frontend
    ports:
      - "80:3000"
    links:
      - server
    depends_on:
      - server
